### ISSUE TITLE
Update on official kernel situation

### ISSUE THREAD

**Issue by MirkoCovizzi** [dencel007/android_kernel_xiaomi_davinci#1]
Hi.
We are currently investigating Mi 9T / K20 official source kernel problems.
You can follow the situation closely [on the issue here](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/1116) and [here](https://github.com/davinci-dev/android_kernel_xiaomi_davinci/issues/1).

Thanks for your support. Any help is accepted.

**Comment by dencel007** [comment]
Hello,
Thanks for the support from your side. 
We will work together and fix this ASAP.

**Comment by MirkoCovizzi** [comment]
Do you already have the device for testing?

**Comment by dencel007** [comment]
@MirkoCovizzi 
I do own a `davinci`. 
First of all, let me try to build the source.
